import type { Metadata } from "next";
import "./globals.css";
import Header from "./(home)/components/header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Header />
				<Toaster />
				<main className='bg-light-surface'>{children}</main>
			</body>
		</html>
	);
}
